

services:
  db:
    image: mysql:latest
    container_name: hotel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel
      MYSQL_USER: uaimUser
      MYSQL_PASSWORD: uaimPassword
    volumes:    
      - db_data:/var/lib/mysql
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      hotel_network:
        ipv4_address: 172.20.0.60

  backend:
    build:
      context: ./backend
    container_name: hotel_backend
    environment:
      FLASK_APP: app.run:app
      FLASK_ENV: development
      DB_HOST: db
      DB_NAME: hotel
      DB_USER: uaimUser
      DB_PASS: uaimPassword
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      hotel_network:
        ipv4_address: 172.20.0.40

  frontend:
    build:
      context: ./spa
    container_name: hotel_frontend
    ports:
      - "80:80"
    networks:
      hotel_network:
        ipv4_address: 172.20.0.20
    depends_on:
      - backend

networks:
  hotel_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  db_data:
    driver: local

